pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Build') {
            steps {
                echo 'building'
            }
        }
        stage('Deploy') {
            steps {
                echo 'depolying'
            }
        }
        stage('Test') {
            steps {
                echo 'testing'
            }
        }
        stage('Release') {
            steps {
                echo 'releasing'
            }
        }
    }
}