# Deploying docker container using ansible
- name: running nginx using docker container and deploying on locahost
  hosts: localhost
  connection: local
  tasks:
    - name: deploy nginx docker container
      docker_container:
        image: nginx:latest
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "8008:80"