-- CREATING AND STATING THE ELEMENTS INTO THE TABLE ALONG WITH CONSTRAIJNTS

CREATE TABLE STUDENTS(
-- id integer,
  ID INT UNIQUE,
  NAME VARCHAR(99),
-- name text,
  MAJOR VARCHAR(99) DEFAULT 'UNDECIDED',
  PRIMARY KEY(ID)
);


-- DESCRINING THE TABLE AND ALTERING IT

-- DESCRIBE STUDENTS;
ALTER TABLE STUDENTS ADD GPA DECIMAL(2,2);
ALTER TABLE STUDENTS DROP GPA;

--  INSERTING DATA INTO THE TABLE

INSERT INTO STUDENTS VALUES(1,"HERO",DEFAULT);
INSERT INTO STUDENTS(ID,NAME, MAJOR) VALUES(2,"HERO1", NULL);
INSERT INTO STUDENTS VALUES(3,'HERO','BIO');
INSERT INTO STUDENTS VALUES(4,'HERO','MATH');

-- MODIFYING STATE OF TABLES
ALTER TABLE STUDENTS
MODIFY NAME VARCHAR(32) NOT NULL;


--  UPDATING AND DELETING

UPDATE STUDENTS
SET MAJOR = 'BIOMATH'
WHERE MAJOR = 'BIO' OR MAJOR = 'MATH';

DELETE FROM STUDENTS
WHERE MAJOR = 'BIOMATH';


--            QUIRY

SELECT * FROM STUDENTS;
--    MORE SPECIFYING THE CONTENT WE WANT TO ACCESS
SELECT ID, MAJOR FROM STUDENTS WHERE ID >1 ORDER BY ID DESC;

SELECT STUDENTS.MAJOR, STUDENTS.ID FROM STUDENTS WHERE MAJOR = 'BIOMATH';

SELECT* FROM STUDENTS ORDER BY NAME, MAJOR, ID LIMIT 3;

SELECT * FROM STUDENTS
WHERE NAME IN ('HERO','HERO1') AND ID >1 AND MAJOR IN ('BIOMATH'); 
-- WHERE MAJOR IN ('BIOMATH');
